/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jxs' at '6/18/16 2:14 PM' with Gradle 2.14
 *
 * @author jxs, @date 6/18/16 2:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
